# Generated by Django 3.1.4 on 2021-04-13 11:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210412_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('coding', 'coding'), ('sports', 'sports'), ('arts', 'arts'), ('travelling', 'travelling'), ('dance', 'dance'), ('coding tutorial', 'coding tutorial')], default='coding', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
